version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/www/app
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - START_COMMAND=${START_COMMAND:-start}
      - PORT=${PORT:-3000}
    command: sh -c "npm install && npm run $START_COMMAND"
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    command: "npm run $START_COMMAND"
    ports:
      - "5432:5432"
